feign:
  gif-service:
    name: Giphy
    url: https://api.giphy.com
    app-id: cvIqh1mSyZxurM1LvU5F70j4oxJVpWMh
  rate-service:
    name: OpenExchangeRates
    url: https://openexchangerates.org
    app-id: c5331769149f4f59bd5afce1b0076d45
    base-currency: USD
    symbols: RUB

json:
  inner:
    path: src/main/java/ru/petrukhin/alexgif/inner/inner.json
  outer:
    path: src/main/java/ru/petrukhin/alexgif/outer/outer.json